Homework/fa17-hw3/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: redirect('/students/new')
  get '/teachers/new', to: 'teachers#new'
  get '/teachers', to: 'teachers#new'
  post '/teachers', to: 'teachers#create'
  get '/students/new', to: 'students#new'
  get '/teachers', to: 'teachers#new'
  post '/students/new', to: 'students#create'
end

Homework/fa17-hw3/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Homework/fa17-hw3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Homework/fa17-hw3/app/controllers/students_controller.rb
class StudentsController < ApplicationController
    def new
        @placeholder_name = 'Taj Shaik'
        @placeholder_gender = 'Male'
        @placeholder_year = '2021'
    end
    def create
        @full_name = params[:full_name]
        @gender = params[:gender]
        @year = params[:year]
      render 'show'
    end
end

Homework/fa17-hw3/app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  def new
    @placeholder_course = '186'
  end

  def create
    @full_name = params[:full_name]
    @course = params[:course]
    @grade_level = params[:grade_level]
    render 'show'
  end
end

Homework/fa17-hw3/app/helpers/application_helper.rb
module ApplicationHelper
end

Homework/fa17-hw3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fa17Hw3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

Homework/fa17-hw3/app/views/teachers/new.html.erb
<%= form_tag teachers_path do %>
  <%= label_tag(:full_name, "Full name") %>
  <%= text_field_tag(:full_name) %>

  <%= label_tag(:course_name, "Course name") %>
  <%= text_field_tag(:course_name, nil, placeholder: @placeholder_course) %>

  <%= label_tag(:grade_level, "Grade level") %>
  <%= text_field_tag(:grade_level) %>

  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <%= submit_tag("Create teacher") %>
<% end %>

<!--
NOTE: The form above is exactly identical to the below HTML form. It purely uses rails helper methods to create the form. Take some time to understand you can utilize the rails helper methods to customize forms juast as you would normal HTML forms. :)

<form action="/teachers" method="POST">
  <label>Full name</label>
  <input name="full_name" type="text"></input>
  <label>Course name</label>
  <input
    name="course"
    placeholder=<%= @placeholder_course %>
    type="text"
  >
  </input>
  <label>Grade level</label>
  <input name="grade_level" type="text"></input>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <button type="submit">Create teacher</button>
</form>
-->

Homework/fa17-hw3/app/views/teachers/show.html.erb
<div>
  <h2>Your form inputs</h2>
  <h4>Full name</h4>
  <h3>
    <%= @full_name %>
  </h3>
  <h4>Course</h4>
  <h3>
    <%= @course %>
  </h3>
  <h4>Grade level</h4>
  <h3>
    <%= @grade_level %>
  </h3>
</div>